### ISSUE TITLE
Failing to compile for iOS

### ISSUE THREAD

**Issue by zwells** [HyperSense-Software/hss-okta-flutter#32]
```Xcode build done.                                           11.1s
Failed to build iOS app
Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): Switch must be exhaustive
/Users/zwells/.pub-cache/hosted/pub.dev/hss_okta_flutter-1.3.2/ios/Classes/HssOktaFlutterPlugin.swift:56:24

**Comment by aldrin233** [comment]
@zwells Can you give me your xcode and flutter versions

**Comment by zwells** [comment]
Xcode is 15.1
Flutter is 3.16.5

**Comment by aldrin233** [comment]
@zwells can you confirm that you are running the app with iOS 17?

**Comment by zwells** [comment]
Yes, 17.2.1

**Comment by aldrin233** [comment]
@zwells do you have the same issue when running with a device/simulator with iOS targetting below 17.0

**Comment by zwells** [comment]
Ran `flutter clean` and targeted iOS 16.4 simulator:

```Launching lib/main.dart on iPhone 14 in debug mode...
Xcode build done.                                           106.4s
Failed to build iOS app
Swift Compiler Error (Xcode): Switch must be exhaustive
/Users/zwells/.pub-cache/hosted/pub.dev/hss_okta_flutter-1.3.2/ios/Classes/HssOktaFlutterPlugin.swift:56:24

Uncategorized (Xcode): Command SwiftCompile failed with a nonzero exit code

Could not build the application for the simulator.
Error launching application on iPhone 14.

Exited (1).```

**Comment by aldrin233** [comment]
Numerous attempts on our side failed to replicate the issue, will be on hold for now.

**Comment by xhirazi** [comment]
+1

**Comment by xhirazi** [comment]
@zwells @aldrin233 

Fix issue in this [PR](https://github.com/HyperSense-Software/hss-okta-flutter/pull/34)

**Comment by xhirazi** [comment]
@zwells 

You can use this
`hss_okta_flutter:
    git:
      url: git@github.com:xhirazi/hss-okta-flutter.git
      path: hss_okta_flutter
      ref: main`
      
in pubspec.yml until the approval of PR.
