### ISSUE TITLE
No named parameter with the name 'tokenToRefresh'

### ISSUE THREAD

**Issue by felixn-unity** [HyperSense-Software/hss-okta-flutter#42]
Hi

I just pulled down latest and tried to run the iOS example, but I get this error when compiling?

Error (Xcode): lib/web/web_profile_screen.dart:45:25: Error: No named parameter with the name 'tokenToRefresh'

**Comment by aldrin233** [comment]
Hi! thanks for reporting a bug, can you confirm that you're on `hss_okta:1.4.1`? you can do a flutter clean and rebuild.

**Comment by felixn-unity** [comment]
Let me verify or pull it ones again, thanks

**Comment by felixn-unity** [comment]
Your branch is up to date with 'origin/main'.


flutter build ipa
Resolving dependencies...
  _fe_analyzer_shared 61.0.0 (68.0.0 available)
  analyzer 5.13.0 (6.5.0 available)
  args 2.4.2 (2.5.0 available)
  cupertino_icons 1.0.6 (1.0.8 available)
  flutter_lints 2.0.3 (3.0.2 available)
  js 0.6.7 (0.7.1 available)
  leak_tracker 10.0.0 (10.0.5 available)
  leak_tracker_flutter_testing 2.0.1 (3.0.5 available)
  leak_tracker_testing 2.0.1 (3.0.1 available)
  lints 2.1.1 (3.0.0 available)
  material_color_utilities 0.8.0 (0.11.1 available)
  meta 1.11.0 (1.15.0 available)
  pigeon 13.0.0 (18.0.1 available)
  plugin_platform_interface 2.1.6 (2.1.8 available)
  test_api 0.6.1 (0.7.1 available)
  url_launcher 6.2.1 (6.2.6 available)
  url_launcher_android 6.2.0 (6.3.1 available)
  url_launcher_ios 6.2.0 (6.2.5 available)
  url_launcher_linux 3.1.0 (3.1.1 available)
  url_launcher_platform_interface 2.2.0 (2.3.2 available)
  url_launcher_web 2.2.0 (2.3.1 available)
  url_launcher_windows 3.1.0 (3.1.1 available)
  vm_service 13.0.0 (14.2.2 available)
Got dependencies!
23 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

Archiving xxxx.hssOktaFlutterExample...
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Automatically signing iOS for device deployment using specified development team in Xcode project: XXXXXXX
Running pod install...                                           1,406ms
Running Xcode build...
Xcode archive done.                                         22.4s
Failed to build iOS app
Error (Xcode): lib/web/web_profile_screen.dart:44:25: Error: No named parameter with the name 'tokenToRefresh'.


Encountered error while archiving for device.

**Comment by aldrin233** [comment]
thank you for providing your output, the fix will be issued in a couple of hours
