### ISSUE TITLE
Error: LateInitializationError: Field 'auth' has not been initialized.

### ISSUE THREAD

**Issue by vkozinec** [HyperSense-Software/hss-okta-flutter#45]
Hello,

when running example app and trying to open app in chrome `flutter run -d chrome`, upon clicking sign in with browser, we get this error:

`Error: LateInitializationError: Field 'auth' has not been initialized.`

**Comment by aldrin233** [comment]
Hi, Make sure you have the correct configurations inside oktaConfig in `HssOktaFlutterWeb().initialize()`

do a full flutter clean, and try again, if the problem persists please contact me. i just ran the example app and i don't encounter that error
